<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'articles/ajaxform' => 'Ajax Form',
    'article_blog_list' => 'Blog - list',
    'article_blog_post' => 'blog-single post',
  ),
  'page' => 
  array (
    'page_blog' => 'Blog - list',
    'page_blog_post' => 'Blog Post',
    'calendar' => 'Calendar',
    'page_contact' => 'Contact',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
    'Search' => 'Search',
  ),
);


/* Auto generated by Themes Administration on : 2014.10.17 08:15:31 */
