<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'searching' => 'Search',
	'Calendar' => 'Eventcalendar',
	'rss' => 'Rss',
	'comments' => 'Comments',
	'guestbooks' => 'guestbooks',
	'ajaxform' => 'Ajaxform'
	);

$aliases = array(

	);

$disable_controller = array(
'guestbooks'
	);



/* Auto generated by Modules Administration on : 2014.11.02 13:20:19 */
