<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'searching' => 'Search',
	'Calendar' => 'Eventcalendar',
	'rss' => 'Rss',
	'comments' => 'Comments',
	'guestbooks' => 'guestbooks'
	);

$aliases = array(

	);

$disable_controller = array(
'guestbooks'
	);



/* Auto generated by Modules Administration on : 2014.10.24 11:23:06 */
