<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'searching' => 'Search',
	'Calendar' => 'Eventcalendar',
	'rss' => 'Rss',
	'comments' => 'Comments'
	);

$aliases = array(

	);

$disable_controller = array(
'Calendar'
	);



/* Auto generated by Modules Administration on : 2014.10.17 09:20:47 */
